### ISSUE TITLE
ElasticCache instance CREATE_FAIL

### ISSUE THREAD

**Issue by navasim** [aws-quickstart/quickstart-magento#21]
Hello,

We are trying to create magento stack using default template provided ( https://s3.amazonaws.com/quickstart-reference/magento/latest/templates/magento-master.template) we have followed each and every line on the documentation provided (http://docs.aws.amazon.com/quickstart/latest/magento/welcome.html). 

Issue:
when process start creating Elastic Cache instances it , it fails the process on ElastiCacheCluster.

Note:
We tried with 2 different regions ( Ireland and Oregon ) result is same.

**Comment by santiagocardenas** [comment]
@navasim 
What error do you see? Have you tried deploying it with Rollback on Failure disabled?

**Comment by navasim** [comment]
it only says ElastiCacheCluster CREATE_FAILED , there are no other reasons ( i don't find any further details in Events tab of stack ), No i have not tried with Rollback failure disabled.

**Comment by santiagocardenas** [comment]
Try it out with rollback disabled and let us know and reopen this with any error messages you see in the nested stack. Be sure to then delete the master stack (which will delete all nested stacks) so that you are not left with resources hanging around because of the disabling of the rollback.
