### ISSUE TITLE
quick question

### ISSUE THREAD

**Issue by abolnasr** [aws-quickstart/quickstart-magento#22]
It's an amazing architecture and works like a charm, speed and performance wise.
However, we're facing an issue.
We wanted to customize the magento and install new themes and extensions.
So are not sure where to do that. If we manage to access the current magento webserver and use it to upload the files and so, it worked fine until the cloudformation decided that the instance is not healthy and deployed a new instance and terminated the one we were working on. That resulted in us losing all progress as the new instance came as fresh new magento installation, without any of the files we added.

Can you please guide me where to update my files permanently? Like do I do that through S3 bucket or Git or what? I'm really confused.

We tried a quick fix by making the EFS work with all of  /var/www/html  instea of just /var/www/html/pub/media and we tested by terminating the instance, it deployed a new one with our files updated and everything. However this came at a price we can't afford; speed & performance were crazy bad (load speed of an empty magento homepage would take more than 40 seconds compared to the 1.7 seconds it used to do). So we know now, this is not the way to go.

I would really appreciate your help and support as we don't have a cloud guru on the team.

Many thanks :)

**Comment by santiagocardenas** [comment]
This sounds more like a Magento internals type of question. What I can think of right away is that you can possibly update the bootstrapping script to include any files that you want to be added to the AMI that's being baked as part of the deployment.

**Comment by n2ctech** [comment]
did you find a fix @abolnasr  ?

**Comment by abolnasr** [comment]
@santiagocardenas yes we got it fixed, that's how we made it work. Thank you very much
