### ISSUE TITLE
Estimate cost does not work

### ISSUE THREAD

**Issue by tienlx93** [aws-quickstart/quickstart-magento#25]
After input information on step Select Template, Specify Details, Options on AWS CloudFormation, I cannot get the Estimate cost
![image](https://user-images.githubusercontent.com/9817634/35050703-018238b0-fbd6-11e7-8e4e-10cb980eb016.png)

Reference link: http://calculator.s3.amazonaws.com/index.html?key=cloudformation/023a7e70-b8ac-45df-bfc6-331109ec3e68

Please help us if this option is available or not, or the template is not working?

**Comment by pangdaxing23** [comment]
+1

**Comment by piyushjalan02** [comment]
Which cost you are looking for in Cloud formation console? Please elaborate.

**Comment by avattathil** [comment]
Closing due to no response (please reopen as needed)
