### ISSUE TITLE
Nginx configuration - expires header for static files not working

### ISSUE THREAD

**Issue by manojVivek** [aws-quickstart/quickstart-magento#29]
The default nginx configuration sets the expires value as `expires +1y` for the `/static` and `/media` location blocks in the file `/scripts/install_magento.sh`. 
That's is not working as expected. It sends the expires header a current time. 
It should be `expires 1y;` to work as expected.

I have a raised a #30 pull request with the fix.

**Comment by sshvans** [comment]
Thanks @manojVivek !
