### ISSUE TITLE
Varnish

### ISSUE THREAD

**Issue by sebfie** [aws-quickstart/quickstart-magento#32]
Hello,

I started to learn aws with this getting started but I have a question : 
- Why varnish is not present in this stack?

Thx

**Comment by piyushjalan02** [comment]
Varnish can be installed inside your EC2 server. If you want, you can include it in 'User Data' in the CFN template or you can install it manually after launching the stack.

**Comment by avattathil** [comment]
PRs are encouraged to add this feature. Closing as it is not on our roadmap
