### ISSUE TITLE
What is the purpose of the Nat Gateway?

### ISSUE THREAD

**Issue by mateusrangel** [aws-quickstart/quickstart-magento#34]
in the Nat Gateway documentation, AWS only talk about the use case of protecting instances in a private subnet from the internet, but this is the case in that Magento Ref Arch? Magento servers need to be facing the internet to clients access the store.

**Comment by mvanbaak** [comment]
The instances are running in a private subnet. This means they can't access the internet.
This is where the NAT Gateways come in play. When the instances need to reach the internet, they go through the NAT gateways.

To access the store from the internet, you do not connect directly to the instances, but you connect to the loadbalancer, which knows how to contact the instances.
