### ISSUE TITLE
Quickstart template needs to be updated about EFS.

### ISSUE THREAD

**Issue by kenzfoo** [aws-quickstart/quickstart-magento#38]
Hi, 

Quickstart template needs to be updated about EFS.
ap-northeast-1 reagion cat use EFS.
https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/?nc1=h_ls

please check it.
thnx.

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/quickstart-magento/commit/03a901e19da58dff27e3f2396311636509bd99f1
