### ISSUE TITLE
Availability Zones: EU not avaiable

### ISSUE THREAD

**Issue by jesperbrejning** [aws-quickstart/quickstart-magento#41]
Hi, 

We can not choose any availability zones i EU. 

How can we add eu-west-2 or eu-north-1 to this template?

**Comment by jesperbrejning** [comment]
From january 2019 Amazon EFS is avaiable in eu-west-2. 

How can we add eu-west-2 to the template ?

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/quickstart-magento/commit/03a901e19da58dff27e3f2396311636509bd99f1
