### ISSUE TITLE
Add support for regions were EFS is available

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/quickstart-magento#43]
- ap-northeast-1
- ap-northeast-2
-  ap-south-1
-  ap-southeast-1
-  ca-central-1
-  eu-west-2

**Comment by avattathil** [comment]
Resolves: https://github.com/aws-quickstart/quickstart-magento/issues/41
Resolves: https://github.com/aws-quickstart/quickstart-magento/issues/38
Resolves: https://github.com/aws-quickstart/quickstart-magento/issues/35

**Comment by brunobertechini** [comment]
sa-east-1 is also available and the template is still preventing it from install. I have manually updated the template to remove sa-east-1 from the rules and it worked fine.
