### ISSUE TITLE
Submodule cannot be cloned

### ISSUE THREAD

**Issue by tomas-st** [aws-quickstart/quickstart-magento#51]
Hi,

when I clone quickstart-magento and afterwards doing a:
git submodule update --init --recursive

it gives me 
Failed to clone 'submodules/quickstart-amazon-aurora-mysql'. Retry scheduled

Search on github only show version for postgres
https://github.com/aws-quickstart?utf8=%E2%9C%93&q=quickstart-amazon-aurora&type=&language=

Was 'submodules/quickstart-amazon-aurora-mysql' accidentially made private?

Thanks
Tom

**Comment by andrew-glenn** [comment]
Hey Tom, Thanks. It was supposed to be public. We've ironed this out.
