### ISSUE TITLE
ap-southeast-1 issues

### ISSUE THREAD

**Issue by troy-ameigh** [aws-quickstart/quickstart-magento#54]
Which was failing due with issue on Stack Events: WaitCondition received failed message: 'Build Process Complete' for uniqueId: <instance-id>

StackARN in my Account: arn:aws:cloudformation:ap-southeast-1:320537072716:stack/Magento/eabad0a0-6a24-11ea-97c6-0a1335ff27ae

K2 link for above: https://k2.amazon.com/workbench/scripts/aws/ChronosCFN?_source=asgard#/stac...

Logs:
PHP Parse error: syntax error, unexpected ''session'' (T_CONSTANT_ENCAPSED_STRING), expecting ']' in /var/www/html/app/etc/env.php on line 11
PHP Parse error: syntax error, unexpected ''session'' (T_CONSTANT_ENCAPSED_STRING), expecting ']' in /var/www/html/app/etc/env.php on line 11
CloudFormation signaled successfully with FAILURE.

On S3 under Scripts/configure-magento.sh. value for init should be replaced with init_value=`head -n10 /var/www/html/app/etc/env.php`. I'll try this and update more here once it was successful!

**Comment by shiraski** [comment]
Sir Can u help me i done successfully deploy this stack
but i am not find magento installed directory 
please help me 
Thanks
