### ISSUE TITLE
Static files not being fully generated

### ISSUE THREAD

**Issue by odwraca** [aws-quickstart/quickstart-magento#56]
After using this quickstart multiple times in multiple regions, I have found that it is not generating the static content correctly on a fresh install. 

I have repeatedly deployed the CF template and found I can fix it with the following:
php bin/magento cache:flush
php bin/magento indexer:reindex
php bin/magento setup:static-content:deploy

I have not taken the time to figure out why this is occurring, but can confirm it is by up to 10 fresh installs in a new VPC via the quickstart.

**Comment by shiraski** [comment]
where you apply this commands 
is it apply magento root directory ?

**Comment by odwraca** [comment]
It has been nearly 60 days since I created this issue, I will retry now and let you know.

**Comment by odwraca** [comment]
Here is how I recreated this issue:

Launched quick start with the "New VPC" option

I used the latest version with sample data:
magento-ce-2.3.5-p1_sample_data-2020-04-24-10-29-49.tar.gz

Once CloudFormation launched, this is what I got:
![Snip20200602_9](https://user-images.githubusercontent.com/45674878/83539267-6eec2c80-a4bc-11ea-972a-777adef92332.png)

Change directories:
cd /var/www/html/

Ran each of these one after another when done:
php bin/magento cache:flush
php bin/magento indexer:reindex
php bin/magento setup:static-content:deploy

Now I can see the css and static assets loading:

![Snip20200602_10](https://user-images.githubusercontent.com/45674878/83540598-2afa2700-a4be-11ea-8a84-d76ca22e5188.png)

**Comment by shiraski** [comment]
But my case i am using amazone Linux 2 but surprise there no www folder and no magento directory

**Comment by odwraca** [comment]
When you used the cloudformation template, did it kickout a URL in your outputs section? What option did you use for the template?

**Comment by shiraski** [comment]
Yes i can brows same your attached image condition

![image](https://user-images.githubusercontent.com/52234274/83572438-430b8e00-a532-11ea-8ddd-98b1ae5767b9.png)

static content not loaded (CSS and JavaScript i think)
I connect I try centos and amazone linux 2 but when i connect my linux bastion i am not find any magento files
i think there is one separate instance maybe hosted magento files and www folder in that server but i am not find any IP for login that server 

This is that server name
Magento-MagentoStack-JLJW2XG48OP0-WebServerASGStack-YZ70SLVKDWKJ-Web Server

**Comment by shiraski** [comment]
Bro i fix my sever side issue with aws team
and i got magento directory then i done your comment and solve my issue thanks

**Comment by shiraski** [comment]
after that facing issue with search field try to search i got error bad gateway 502
and i enable varnish full page cache then i got error some products try to open in frond end getting same error

**Comment by davmayd** [comment]
This was resolved by commit https://github.com/aws-quickstart/quickstart-magento/commit/f2a713f4e766d4954bc84fc1f531996b87c30254
