### ISSUE TITLE
Magento Installed DIerectory Not Found

### ISSUE THREAD

**Issue by shiraski** [aws-quickstart/quickstart-magento#62]
Dear Team
I done deploy this stack but after I login ssh with ec2-user account
but i am not find this magento related any files and folder
please give me location and directory magento installed
also after install magento static and css not loaded

**Comment by shalen-n** [comment]
@shiraski  Inspecting the Scripts folder under this Quick Start, it appears that on the WebServer Instances the:

Root Folder can be found at path >> "/var/www/html" and
Nginx config files can be found at path >> "/etc/nginx"

I've confirmed the same by SSH'ing into the Bastion Host >> Web Server Host . Guide 1 helped me to effectively SSH into the Web Server Host running in the Private Subnets.

**Comment by shiraski** [comment]
This approch is fully wrong dont use this in for production
bcz of this will charge arount monthly 600$
But
