### ISSUE TITLE
Site graphics is not loaded properly

### ISSUE THREAD

**Issue by veltz-avi** [aws-quickstart/quickstart-magento#65]
After successful deployment the main site is not loaded properly.
The issue was solved after executing the following commands from the web server nodes.

From ec2-user run:
cd /var/www/html
php bin/magento setup:static-content:deploy -f
php bin/magento deploy:mode:set developer
sudo service nginx restart

**Comment by davmayd** [comment]
This was resolved by the following commit: https://github.com/aws-quickstart/quickstart-magento/commit/f2a713f4e766d4954bc84fc1f531996b87c30254
