### ISSUE TITLE
404 on JS and style sheets

### ISSUE THREAD

**Issue by fernandoavalos** [aws-quickstart/quickstart-magento#70]
I used this template as it is with Magento 2.3.2 with sample data. 

All the stack completed successfully but the I'm getting 404 erros on:

- calendar.css
- styles.css
- styles-l.css
- require.js
- mixins.js
- polyfill.js
- logo.svg
- print.css

**Comment by davmayd** [comment]
This was resolved by the following commit: https://github.com/aws-quickstart/quickstart-magento/commit/f2a713f4e766d4954bc84fc1f531996b87c30254
