### ISSUE TITLE
magento ce 2.3.4 after installation always return http 500

### ISSUE THREAD

**Issue by newcools** [aws-quickstart/quickstart-magento#73]
they error message says

The following modules are outdated:
Magento_GoogleShoppingAds data: current version - none, required version - 3.0.1
Magento_AuthorizenetAcceptjs data: current version - none, required version - 1.0.0
MSP_ReCaptcha data: current version - none, required version - 1.6.0
Amazon_Core data: current version - none, required version - 3.3.1
Amazon_Login data: current version - none, required version - 3.3.1
Amazon_Payment data: current version - none, required version - 3.3.1
Dotdigitalgroup_Email data: current version - none, required version - 4.1.0
Dotdigitalgroup_Chat data: current version - none, required version - 1.0.0
Klarna_Core data: current version - none, required version - 5.2.3
Klarna_Ordermanagement data: current version - none, required version - 5.0.7
Klarna_Kp data: current version - none, required version - 6.4.0
Magento_PaypalReCaptcha data: current version - none, required version - 2.0.0
MSP_TwoFactorAuth data: current version - none, required version - 3.1.0
Temando_Shipping data: current version - none, required version - 1.6.0
Vertex_Tax data: current version - none, required version - 100.5.1
Vertex_AddressValidation data: current version - none, required version - 100.5.0
Yotpo_Yotpo data: current version - none, required version - 3.0.1 at /var/www/html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php:66)"} []
[2020-10-25 07:03:12] main.CRITICAL: Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
Magento_GoogleShoppingAds data: current version - none, required version - 3.0.1
Magento_AuthorizenetAcceptjs data: current version - none, required version - 1.0.0
MSP_ReCaptcha data: current version - none, required version - 1.6.0
Amazon_Core data: current version - none, required version - 3.3.1
Amazon_Login data: current version - none, required version - 3.3.1
Amazon_Payment data: current version - none, required version - 3.3.1
Dotdigitalgroup_Email data: current version - none, required version - 4.1.0
Dotdigitalgroup_Chat data: current version - none, required version - 1.0.0
Klarna_Core data: current version - none, required version - 5.2.3
Klarna_Ordermanagement data: current version - none, required version - 5.0.7
Klarna_Kp data: current version - none, required version - 6.4.0
Magento_PaypalReCaptcha data: current version - none, required version - 2.0.0
MSP_TwoFactorAuth data: current version - none, required version - 3.1.0
Temando_Shipping data: current version - none, required version - 1.6.0
Vertex_Tax data: current version - none, required version - 100.5.1
Vertex_AddressValidation data: current version - none, required version - 100.5.0
Yotpo_Yotpo data: current version - none, required version - 3.0.1 {"report_id":"a9ddc42e18445ff98a7a3ac0a80038c26871bc3035a54cb6f4f7f6d669aeeb92","exception":"[object] (Magento\\Framework\\Exception\\LocalizedException(code: 0): Please upgrade your database: Run \"bin/magento setup:upgrade\" from the Magento root directory.
The following modules are outdated:
Magento_GoogleShoppingAds data: current version - none, required version - 3.0.1
Magento_AuthorizenetAcceptjs data: current version - none, required version - 1.0.0
MSP_ReCaptcha data: current version - none, required version - 1.6.0
Amazon_Core data: current version - none, required version - 3.3.1
Amazon_Login data: current version - none, required version - 3.3.1
Amazon_Payment data: current version - none, required version - 3.3.1
Dotdigitalgroup_Email data: current version - none, required version - 4.1.0
Dotdigitalgroup_Chat data: current version - none, required version - 1.0.0
Klarna_Core data: current version - none, required version - 5.2.3
Klarna_Ordermanagement data: current version - none, required version - 5.0.7
Klarna_Kp data: current version - none, required version - 6.4.0
Magento_PaypalReCaptcha data: current version - none, required version - 2.0.0
MSP_TwoFactorAuth data: current version - none, required version - 3.1.0
Temando_Shipping data: current version - none, required version - 1.6.0
Vertex_Tax data: current version - none, required version - 100.5.1
Vertex_AddressValidation data: current version - none, required version - 100.5.0
Yotpo_Yotpo data: current version - none, required version - 3.0.1 at /var/www/html/vendor/magento/framework/Module/Plugin/DbStatusValidator.php:66)"} []

**Comment by newcools** [comment]
apparently, 2.3.4 is not supported. 2.3.2-p2 works fine though

**Comment by davmayd** [comment]
This Quick Start supports Magento 2.1.18 or 2.3.2, it has not been updated to reflect new releases
