### ISSUE TITLE
Does this Quick Start support Magento 2.4?

### ISSUE THREAD

**Issue by irnjunior** [aws-quickstart/quickstart-magento#74]
Does this Quick Start support Magento 2.4?

**Comment by davmayd** [comment]
This Quick Start supports versions 2.1.18 or 2.3.2, it does not support 2.4

**Comment by roopemerikukka** [comment]
Does this also mean that it doesn't work with 2.4 or it just has not been tested with it? In general is there a recommended path how to update/upgrade Magento version when it has been deployed using these templates? Do you just replace the file in S3 with newer one and re-deploy?

**Comment by davmayd** [comment]
It does not work with 2.4, the deployment fails

**Comment by davmayd** [comment]
@irnjunior @roopemerikukka the Quick Start currently supports 2.1.18 or 2.3.2. Attempting to deploy with 2.4 installation media causes it to fail. If you're able to update it to support 2.4 feel free to submit a pull request.
